package store

import "fmt"

// InitSchema создаёт схему БД если она не существует
func (db *DB) InitSchema() error {
	statements := []string{
		`CREATE TABLE IF NOT EXISTS scan_runs (
			id BIGSERIAL PRIMARY KEY,
			root_path TEXT NOT NULL,
			started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
			finished_at TIMESTAMPTZ,
			status TEXT NOT NULL,
			files_scanned INTEGER NOT NULL DEFAULT 0,
			files_indexed INTEGER NOT NULL DEFAULT 0,
			errors_count INTEGER NOT NULL DEFAULT 0
		)`,
		`CREATE TABLE IF NOT EXISTS ds_products (
			id BIGSERIAL PRIMARY KEY,
			product_name TEXT NOT NULL,
			created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
			updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
		)`,
		`CREATE TABLE IF NOT EXISTS files (
			id BIGSERIAL PRIMARY KEY,
			scan_run_id BIGINT NOT NULL REFERENCES scan_runs(id) ON DELETE CASCADE,
			ds_product_id BIGINT REFERENCES ds_products(id) ON DELETE SET NULL,
			path TEXT NOT NULL,
			rel_path TEXT NOT NULL,
			extension TEXT NOT NULL,
			size_bytes BIGINT NOT NULL DEFAULT 0,
			hash_sha256 TEXT NOT NULL,
			modified_at TIMESTAMPTZ NOT NULL,
			encoding TEXT,
			language TEXT,
			created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
			updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
		)`,
		`CREATE TABLE IF NOT EXISTS symbols (
			id BIGSERIAL PRIMARY KEY,
			file_id BIGINT NOT NULL REFERENCES files(id) ON DELETE CASCADE,
			symbol_name TEXT NOT NULL,
			symbol_type TEXT NOT NULL,
			entity_type TEXT NOT NULL,
			entity_id BIGINT NOT NULL,
			line_number INTEGER NOT NULL DEFAULT 0,
			signature TEXT
		)`,
		`CREATE TABLE IF NOT EXISTS sql_procedures (
			id BIGSERIAL PRIMARY KEY,
			file_id BIGINT NOT NULL REFERENCES files(id) ON DELETE CASCADE,
			proc_name TEXT NOT NULL,
			parameters JSONB,
			line_start INTEGER NOT NULL DEFAULT 0,
			line_end INTEGER NOT NULL DEFAULT 0,
			body_hash TEXT
		)`,
		`CREATE TABLE IF NOT EXISTS sql_tables (
			id BIGSERIAL PRIMARY KEY,
			file_id BIGINT NOT NULL REFERENCES files(id) ON DELETE CASCADE,
			table_name TEXT NOT NULL,
			context TEXT NOT NULL,
			is_temporary BOOLEAN NOT NULL DEFAULT FALSE,
			line_number INTEGER NOT NULL DEFAULT 0,
			column_number INTEGER
		)`,
		`CREATE TABLE IF NOT EXISTS sql_columns (
			id BIGSERIAL PRIMARY KEY,
			file_id BIGINT NOT NULL REFERENCES files(id) ON DELETE CASCADE,
			table_name TEXT NOT NULL,
			column_name TEXT NOT NULL,
			line_number INTEGER NOT NULL DEFAULT 0,
			column_number INTEGER
		)`,
		`CREATE TABLE IF NOT EXISTS sql_column_definitions (
			id BIGSERIAL PRIMARY KEY,
			file_id BIGINT NOT NULL REFERENCES files(id) ON DELETE CASCADE,
			table_name TEXT NOT NULL,
			column_name TEXT NOT NULL,
			data_type TEXT NOT NULL,
			definition_kind TEXT NOT NULL DEFAULT 'create_table',
			line_number INTEGER NOT NULL DEFAULT 0,
			column_order INTEGER NOT NULL DEFAULT 0
		)`,
		`CREATE TABLE IF NOT EXISTS sql_index_definitions (
			id BIGSERIAL PRIMARY KEY,
			file_id BIGINT NOT NULL REFERENCES files(id) ON DELETE CASCADE,
			table_name TEXT NOT NULL,
			index_name TEXT NOT NULL,
			index_fields TEXT,
			index_type TEXT,
			is_unique BOOLEAN NOT NULL DEFAULT FALSE,
			definition_kind TEXT NOT NULL DEFAULT 'create_index',
			line_number INTEGER NOT NULL DEFAULT 0
		)`,
		`CREATE TABLE IF NOT EXISTS sql_index_definition_fields (
			id BIGSERIAL PRIMARY KEY,
			table_index_id BIGINT NOT NULL REFERENCES sql_index_definitions(id) ON DELETE CASCADE,
			field_name TEXT NOT NULL,
			field_order INTEGER NOT NULL DEFAULT 0,
			line_number INTEGER NOT NULL DEFAULT 0
		)`,
		`CREATE TABLE IF NOT EXISTS pas_units (
			id BIGSERIAL PRIMARY KEY,
			file_id BIGINT NOT NULL REFERENCES files(id) ON DELETE CASCADE,
			unit_name TEXT NOT NULL,
			interface_uses JSONB,
			implementation_uses JSONB,
			line_start INTEGER NOT NULL DEFAULT 0,
			line_end INTEGER NOT NULL DEFAULT 0
		)`,
		`CREATE TABLE IF NOT EXISTS h_files_defines (
			id BIGSERIAL PRIMARY KEY,
			file_id BIGINT NOT NULL REFERENCES files(id) ON DELETE CASCADE,
			define_name TEXT NOT NULL,
			define_value TEXT,
			define_type TEXT NOT NULL,
			line_number INTEGER NOT NULL DEFAULT 0
		)`,
		`CREATE TABLE IF NOT EXISTS js_functions (
			id BIGSERIAL PRIMARY KEY,
			file_id BIGINT NOT NULL REFERENCES files(id) ON DELETE CASCADE,
			function_name TEXT NOT NULL,
			signature TEXT,
			line_start INTEGER NOT NULL DEFAULT 0,
			line_end INTEGER NOT NULL DEFAULT 0,
			scenario_type TEXT,
			parent_object TEXT
		)`,
		`CREATE TABLE IF NOT EXISTS js_constants (
			id BIGSERIAL PRIMARY KEY,
			file_id BIGINT NOT NULL REFERENCES files(id) ON DELETE CASCADE,
			constant_name TEXT NOT NULL,
			constant_value TEXT,
			line_number INTEGER NOT NULL DEFAULT 0
		)`,
		`CREATE TABLE IF NOT EXISTS smf_instruments (
			id BIGSERIAL PRIMARY KEY,
			file_id BIGINT NOT NULL REFERENCES files(id) ON DELETE CASCADE,
			instrument_name TEXT NOT NULL,
			brief TEXT,
			deal_object_id BIGINT,
			ds_module_id BIGINT,
			start_state TEXT,
			scenario_type TEXT,
			states JSONB,
			actions JSONB,
			accounts JSONB
		)`,
		`CREATE TABLE IF NOT EXISTS dfm_forms (
			id BIGSERIAL PRIMARY KEY,
			file_id BIGINT NOT NULL REFERENCES files(id) ON DELETE CASCADE,
			form_name TEXT NOT NULL,
			form_class TEXT NOT NULL,
			caption TEXT,
			line_start INTEGER NOT NULL DEFAULT 0,
			line_end INTEGER NOT NULL DEFAULT 0
		)`,
		`CREATE TABLE IF NOT EXISTS dfm_components (
			id BIGSERIAL PRIMARY KEY,
			file_id BIGINT NOT NULL REFERENCES files(id) ON DELETE CASCADE,
			form_id BIGINT NOT NULL REFERENCES dfm_forms(id) ON DELETE CASCADE,
			component_name TEXT NOT NULL,
			component_type TEXT NOT NULL,
			parent_name TEXT,
			caption TEXT,
			line_start INTEGER NOT NULL DEFAULT 0,
			line_end INTEGER NOT NULL DEFAULT 0
		)`,
		`CREATE TABLE IF NOT EXISTS report_forms (
			id BIGSERIAL PRIMARY KEY,
			file_id BIGINT NOT NULL REFERENCES files(id) ON DELETE CASCADE,
			report_name TEXT NOT NULL,
			report_type TEXT NOT NULL,
			form_name TEXT,
			form_class TEXT,
			line_start INTEGER NOT NULL DEFAULT 0,
			line_end INTEGER NOT NULL DEFAULT 0
		)`,
		`CREATE TABLE IF NOT EXISTS report_fields (
			id BIGSERIAL PRIMARY KEY,
			report_form_id BIGINT NOT NULL REFERENCES report_forms(id) ON DELETE CASCADE,
			field_name TEXT NOT NULL,
			source_name TEXT,
			format_mask TEXT,
			options JSONB,
			line_number INTEGER NOT NULL DEFAULT 0,
			raw_text TEXT
		)`,
		`CREATE TABLE IF NOT EXISTS report_params (
			id BIGSERIAL PRIMARY KEY,
			report_form_id BIGINT NOT NULL REFERENCES report_forms(id) ON DELETE CASCADE,
			param_name TEXT NOT NULL,
			param_kind TEXT NOT NULL,
			component_type TEXT,
			data_type TEXT,
			lookup_form TEXT,
			lookup_table TEXT,
			lookup_column TEXT,
			key_column TEXT,
			required BOOLEAN NOT NULL DEFAULT FALSE,
			default_value TEXT,
			line_number INTEGER NOT NULL DEFAULT 0,
			raw_text TEXT
		)`,
		`CREATE TABLE IF NOT EXISTS vb_functions (
			id BIGSERIAL PRIMARY KEY,
			report_form_id BIGINT NOT NULL REFERENCES report_forms(id) ON DELETE CASCADE,
			function_name TEXT NOT NULL,
			function_type TEXT NOT NULL,
			signature TEXT,
			body_text TEXT,
			line_start INTEGER NOT NULL DEFAULT 0,
			line_end INTEGER NOT NULL DEFAULT 0,
			body_hash TEXT
		)`,
		`CREATE TABLE IF NOT EXISTS query_fragments (
			id BIGSERIAL PRIMARY KEY,
			file_id BIGINT NOT NULL REFERENCES files(id) ON DELETE CASCADE,
			parent_type TEXT NOT NULL,
			parent_id BIGINT NOT NULL,
			component_name TEXT NOT NULL,
			component_type TEXT NOT NULL,
			query_text TEXT NOT NULL,
			query_hash TEXT,
			tables_referenced JSONB,
			context TEXT NOT NULL,
			line_number INTEGER NOT NULL DEFAULT 0
		)`,
		`CREATE TABLE IF NOT EXISTS include_directives (
			id BIGSERIAL PRIMARY KEY,
			file_id BIGINT NOT NULL REFERENCES files(id) ON DELETE CASCADE,
			include_path TEXT NOT NULL,
			resolved_file_id BIGINT,
			line_number INTEGER NOT NULL DEFAULT 0
		)`,
		`CREATE TABLE IF NOT EXISTS pas_classes (
			id BIGSERIAL PRIMARY KEY,
			unit_id BIGINT,
			class_name TEXT NOT NULL,
			parent_class TEXT,
			dfm_form_id BIGINT,
			line_start INTEGER NOT NULL DEFAULT 0,
			line_end INTEGER NOT NULL DEFAULT 0
		)`,
		`CREATE TABLE IF NOT EXISTS pas_methods (
			id BIGSERIAL PRIMARY KEY,
			class_id BIGINT,
			unit_id BIGINT,
			method_name TEXT NOT NULL,
			signature TEXT,
			visibility TEXT,
			line_number INTEGER NOT NULL DEFAULT 0
		)`,
		`CREATE TABLE IF NOT EXISTS pas_fields (
			id BIGSERIAL PRIMARY KEY,
			class_id BIGINT,
			field_name TEXT NOT NULL,
			field_type TEXT,
			dfm_component_id BIGINT,
			visibility TEXT,
			line_number INTEGER NOT NULL DEFAULT 0
		)`,
		`CREATE TABLE IF NOT EXISTS api_business_objects (
			id BIGSERIAL PRIMARY KEY,
			file_id BIGINT NOT NULL REFERENCES files(id) ON DELETE CASCADE,
			business_object TEXT NOT NULL,
			module_name TEXT,
			line_start INTEGER NOT NULL DEFAULT 0,
			line_end INTEGER NOT NULL DEFAULT 0
		)`,
		`CREATE TABLE IF NOT EXISTS api_contracts (
			id BIGSERIAL PRIMARY KEY,
			file_id BIGINT NOT NULL REFERENCES files(id) ON DELETE CASCADE,
			business_object_id BIGINT,
			business_object TEXT,
			contract_name TEXT NOT NULL,
			contract_kind TEXT NOT NULL,
			object_type_id INTEGER,
			object_name_id BIGINT,
			api_version INTEGER,
			arch_approval INTEGER,
			implemented BOOLEAN NOT NULL DEFAULT FALSE,
			internal_use BOOLEAN NOT NULL DEFAULT FALSE,
			deprecated BOOLEAN NOT NULL DEFAULT FALSE,
			is_external BOOLEAN NOT NULL DEFAULT FALSE,
			owner_module TEXT,
			used_object_name TEXT,
			used_module_sys_name TEXT,
			short_description TEXT,
			full_description TEXT,
			line_start INTEGER NOT NULL DEFAULT 0,
			line_end INTEGER NOT NULL DEFAULT 0
		)`,
		`CREATE TABLE IF NOT EXISTS api_contract_params (
			id BIGSERIAL PRIMARY KEY,
			contract_id BIGINT NOT NULL REFERENCES api_contracts(id) ON DELETE CASCADE,
			direction TEXT NOT NULL,
			param_name TEXT NOT NULL,
			prm_sub_object TEXT,
			type_name TEXT,
			required BOOLEAN NOT NULL DEFAULT FALSE,
			rus_name TEXT,
			description TEXT,
			ws_param_name TEXT,
			param_order INTEGER NOT NULL DEFAULT 0,
			is_virtual_link BOOLEAN NOT NULL DEFAULT FALSE,
			line_number INTEGER NOT NULL DEFAULT 0
		)`,
		`CREATE TABLE IF NOT EXISTS api_contract_tables (
			id BIGSERIAL PRIMARY KEY,
			contract_id BIGINT NOT NULL REFERENCES api_contracts(id) ON DELETE CASCADE,
			direction TEXT NOT NULL,
			table_name TEXT NOT NULL,
			ws_param_name TEXT,
			required BOOLEAN NOT NULL DEFAULT FALSE,
			rus_name TEXT,
			description TEXT,
			param_order INTEGER NOT NULL DEFAULT 0,
			line_number INTEGER NOT NULL DEFAULT 0
		)`,
		`CREATE TABLE IF NOT EXISTS api_contract_table_fields (
			id BIGSERIAL PRIMARY KEY,
			contract_table_id BIGINT NOT NULL REFERENCES api_contract_tables(id) ON DELETE CASCADE,
			field_name TEXT NOT NULL,
			type_name TEXT,
			required BOOLEAN NOT NULL DEFAULT FALSE,
			rus_name TEXT,
			description TEXT,
			ws_param_name TEXT,
			param_order INTEGER NOT NULL DEFAULT 0,
			line_number INTEGER NOT NULL DEFAULT 0
		)`,
		`CREATE TABLE IF NOT EXISTS api_business_object_params (
			id BIGSERIAL PRIMARY KEY,
			file_id BIGINT NOT NULL REFERENCES files(id) ON DELETE CASCADE,
			business_object TEXT NOT NULL,
			param_name TEXT NOT NULL,
			prm_sub_object TEXT,
			type_name TEXT,
			ws_param_name TEXT,
			rus_name TEXT,
			description TEXT,
			line_number INTEGER NOT NULL DEFAULT 0
		)`,
		`CREATE TABLE IF NOT EXISTS api_business_object_tables (
			id BIGSERIAL PRIMARY KEY,
			file_id BIGINT NOT NULL REFERENCES files(id) ON DELETE CASCADE,
			business_object TEXT NOT NULL,
			table_name TEXT NOT NULL,
			type_name TEXT,
			ws_param_name TEXT,
			rus_name TEXT,
			description TEXT,
			line_number INTEGER NOT NULL DEFAULT 0
		)`,
		`CREATE TABLE IF NOT EXISTS api_business_object_table_fields (
			id BIGSERIAL PRIMARY KEY,
			business_table_id BIGINT NOT NULL REFERENCES api_business_object_tables(id) ON DELETE CASCADE,
			field_name TEXT NOT NULL,
			type_name TEXT,
			ws_param_name TEXT,
			rus_name TEXT,
			description TEXT,
			param_order INTEGER NOT NULL DEFAULT 0,
			line_number INTEGER NOT NULL DEFAULT 0
		)`,
		`CREATE TABLE IF NOT EXISTS api_business_object_table_indexes (
			id BIGSERIAL PRIMARY KEY,
			business_table_id BIGINT NOT NULL REFERENCES api_business_object_tables(id) ON DELETE CASCADE,
			index_name TEXT NOT NULL,
			index_fields TEXT,
			index_type INTEGER NOT NULL DEFAULT 0,
			is_clustered BOOLEAN NOT NULL DEFAULT FALSE,
			line_number INTEGER NOT NULL DEFAULT 0
		)`,
		`CREATE TABLE IF NOT EXISTS api_business_object_table_index_fields (
			id BIGSERIAL PRIMARY KEY,
			table_index_id BIGINT NOT NULL REFERENCES api_business_object_table_indexes(id) ON DELETE CASCADE,
			field_name TEXT NOT NULL,
			field_order INTEGER NOT NULL DEFAULT 0,
			line_number INTEGER NOT NULL DEFAULT 0
		)`,
		`CREATE TABLE IF NOT EXISTS api_contract_return_values (
			id BIGSERIAL PRIMARY KEY,
			contract_id BIGINT NOT NULL REFERENCES api_contracts(id) ON DELETE CASCADE,
			value TEXT,
			return_type INTEGER NOT NULL DEFAULT 0,
			description TEXT,
			line_number INTEGER NOT NULL DEFAULT 0
		)`,
		`CREATE TABLE IF NOT EXISTS api_contract_contexts (
			id BIGSERIAL PRIMARY KEY,
			contract_id BIGINT NOT NULL REFERENCES api_contracts(id) ON DELETE CASCADE,
			context_name TEXT,
			type_name TEXT,
			rus_name TEXT,
			description TEXT,
			context_order INTEGER NOT NULL DEFAULT 0,
			context_value TEXT,
			is_virtual_link BOOLEAN NOT NULL DEFAULT FALSE,
			line_number INTEGER NOT NULL DEFAULT 0
		)`,
		`CREATE TABLE IF NOT EXISTS api_macro_invocations (
			id BIGSERIAL PRIMARY KEY,
			file_id BIGINT NOT NULL REFERENCES files(id) ON DELETE CASCADE,
			procedure_name TEXT,
			macro_type TEXT NOT NULL,
			target_name TEXT NOT NULL,
			target_kind TEXT NOT NULL,
			line_number INTEGER NOT NULL DEFAULT 0,
			raw_text TEXT
		)`,
		`CREATE TABLE IF NOT EXISTS relations (
			id BIGSERIAL PRIMARY KEY,
			source_type TEXT NOT NULL,
			source_id BIGINT NOT NULL,
			target_type TEXT NOT NULL,
			target_id BIGINT NOT NULL,
			relation_type TEXT NOT NULL,
			confidence TEXT,
			line_number INTEGER NOT NULL DEFAULT 0
		)`,
		`CREATE TABLE IF NOT EXISTS ds_return_codes (
			id BIGSERIAL PRIMARY KEY,
			file_id BIGINT NOT NULL REFERENCES files(id) ON DELETE CASCADE,
			ret_code BIGINT NOT NULL,
			message TEXT NOT NULL,
			proc_name TEXT,
			module_id INTEGER
		)`,
		`CREATE TABLE IF NOT EXISTS rti_sessions (
			id BIGSERIAL PRIMARY KEY,
			file_path TEXT NOT NULL,
			file_size BIGINT NOT NULL DEFAULT 0,
			parsed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
			total_calls INTEGER NOT NULL DEFAULT 0,
			errors_count INTEGER NOT NULL DEFAULT 0,
			max_nest_level INTEGER NOT NULL DEFAULT 0,
			unparsed_lines INTEGER NOT NULL DEFAULT 0,
			client_events_count INTEGER NOT NULL DEFAULT 0
		)`,
		`CREATE TABLE IF NOT EXISTS rti_calls (
			id BIGSERIAL PRIMARY KEY,
			session_id BIGINT NOT NULL REFERENCES rti_sessions(id) ON DELETE CASCADE,
			procedure TEXT NOT NULL,
			enter_line INTEGER NOT NULL DEFAULT 0,
			exit_line INTEGER NOT NULL DEFAULT 0,
			enter_time TIMESTAMPTZ,
			exit_time TIMESTAMPTZ,
			elapsed_ms INTEGER NOT NULL DEFAULT 0,
			nest_level INTEGER NOT NULL DEFAULT 0,
			module_id INTEGER NOT NULL DEFAULT 0,
			module_name TEXT,
			tran_count INTEGER NOT NULL DEFAULT 0,
			begin_cnt INTEGER NOT NULL DEFAULT 0,
			ret_val INTEGER,
			ret_val_context TEXT,
			parent_id BIGINT,
			spid INTEGER NOT NULL DEFAULT 0
		)`,
		`CREATE TABLE IF NOT EXISTS rti_params (
			id BIGSERIAL PRIMARY KEY,
			call_id BIGINT NOT NULL REFERENCES rti_calls(id) ON DELETE CASCADE,
			name TEXT NOT NULL,
			type TEXT NOT NULL,
			value TEXT
		)`,
		`CREATE TABLE IF NOT EXISTS rti_checkpoints (
			id BIGSERIAL PRIMARY KEY,
			call_id BIGINT NOT NULL REFERENCES rti_calls(id) ON DELETE CASCADE,
			label TEXT NOT NULL,
			timestamp TIMESTAMPTZ,
			elapsed_ms INTEGER NOT NULL DEFAULT 0,
			line_no INTEGER NOT NULL DEFAULT 0
		)`,
		`CREATE TABLE IF NOT EXISTS rti_blog_blocks (
			id         BIGSERIAL PRIMARY KEY,
			session_id BIGINT NOT NULL REFERENCES rti_sessions(id) ON DELETE CASCADE,
			call_id    BIGINT REFERENCES rti_calls(id) ON DELETE CASCADE,
			block_name TEXT NOT NULL,
			enter_time TIMESTAMPTZ,
			exit_time  TIMESTAMPTZ,
			elapsed_ms INTEGER NOT NULL DEFAULT 0,
			enter_line INTEGER NOT NULL DEFAULT 0,
			exit_line  INTEGER NOT NULL DEFAULT 0
		)`,
		`CREATE TABLE IF NOT EXISTS rti_blog_tables (
			id             BIGSERIAL PRIMARY KEY,
			session_id     BIGINT NOT NULL REFERENCES rti_sessions(id) ON DELETE CASCADE,
			call_id        BIGINT REFERENCES rti_calls(id) ON DELETE CASCADE,
			table_name     TEXT NOT NULL,
			columns_header TEXT,
			row_count      INTEGER NOT NULL DEFAULT 0,
			rows_data      TEXT,
			enter_line     INTEGER NOT NULL DEFAULT 0
		)`,
		// ALTER для существующих БД, созданных до появления client_events_count
		// (CREATE TABLE IF NOT EXISTS не добавляет колонки в уже существующую таблицу).
		`ALTER TABLE rti_sessions ADD COLUMN IF NOT EXISTS client_events_count INTEGER NOT NULL DEFAULT 0`,
		`CREATE TABLE IF NOT EXISTS trc_sessions (
			id BIGSERIAL PRIMARY KEY,
			file_path TEXT NOT NULL,
			file_size BIGINT NOT NULL DEFAULT 0,
			parsed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
			total_events INTEGER NOT NULL DEFAULT 0,
			provider_name TEXT,
			server_name TEXT,
			major_version INTEGER NOT NULL DEFAULT 0,
			minor_version INTEGER NOT NULL DEFAULT 0,
			build_number INTEGER NOT NULL DEFAULT 0
		)`,
		`CREATE TABLE IF NOT EXISTS trc_events (
			id             BIGSERIAL PRIMARY KEY,
			session_id     BIGINT NOT NULL REFERENCES trc_sessions(id) ON DELETE CASCADE,
			event_class    INTEGER NOT NULL DEFAULT 0,
			event_name     TEXT,
			text_data      TEXT,
			procedure      TEXT,
			spid           INTEGER,
			database_id    INTEGER,
			database_name  TEXT,
			application_name TEXT,
			login_name     TEXT,
			host_name      TEXT,
			start_time     TIMESTAMPTZ,
			end_time       TIMESTAMPTZ,
			duration_ms    BIGINT NOT NULL DEFAULT 0,
			cpu            BIGINT,
			reads          BIGINT,
			writes         BIGINT,
			row_counts     BIGINT,
			object_id      BIGINT,
			object_name    TEXT,
			event_sequence BIGINT,
			nest_level     INTEGER,
			line_number    INTEGER,
			error          INTEGER,
			severity       INTEGER,
			success        INTEGER,
			params         JSONB,
			columns        JSONB,
			parent_id      BIGINT,
			depth          INTEGER NOT NULL DEFAULT 0
		)`,
		// ALTER для существующих БД, созданных до добавления parent_id/depth
		`ALTER TABLE trc_events ADD COLUMN IF NOT EXISTS parent_id BIGINT`,
		`ALTER TABLE trc_events ADD COLUMN IF NOT EXISTS depth INTEGER NOT NULL DEFAULT 0`,
		`CREATE TABLE IF NOT EXISTS rti_client_events (
			id             BIGSERIAL PRIMARY KEY,
			session_id     BIGINT NOT NULL REFERENCES rti_sessions(id) ON DELETE CASCADE,
			parent_id      BIGINT,
			timestamp      TIMESTAMPTZ,
			level          TEXT,
			category       TEXT,
			class_name     TEXT,
			method_name    TEXT,
			pid            INTEGER NOT NULL DEFAULT 0,
			seq_no         INTEGER NOT NULL DEFAULT 0,
			line_no        INTEGER NOT NULL DEFAULT 0,
			kind           TEXT NOT NULL,
			elapsed_ms     INTEGER NOT NULL DEFAULT 0,
			payload        JSONB,
			server_call_id BIGINT REFERENCES rti_calls(id)
		)`,
		`CREATE EXTENSION IF NOT EXISTS pg_trgm`,
		`CREATE UNIQUE INDEX IF NOT EXISTS idx_ds_products_product_name ON ds_products(product_name)`,
		`CREATE INDEX IF NOT EXISTS idx_files_scan_run_id ON files(scan_run_id)`,
		`CREATE INDEX IF NOT EXISTS idx_files_ds_product_id ON files(ds_product_id)`,
		`CREATE INDEX IF NOT EXISTS idx_files_extension ON files(extension)`,
		`CREATE INDEX IF NOT EXISTS idx_symbols_file_id ON symbols(file_id)`,
		`CREATE INDEX IF NOT EXISTS idx_symbols_symbol_name_lower ON symbols(LOWER(symbol_name))`,
		`CREATE INDEX IF NOT EXISTS idx_symbols_symbol_name_type_lower ON symbols(LOWER(symbol_name), symbol_type)`,
		`CREATE INDEX IF NOT EXISTS idx_symbols_symbol_name_trgm ON symbols USING GIN (symbol_name gin_trgm_ops)`,
		`CREATE INDEX IF NOT EXISTS idx_symbols_signature_trgm ON symbols USING GIN (signature gin_trgm_ops)`,
		`CREATE INDEX IF NOT EXISTS idx_sql_procedures_file_id ON sql_procedures(file_id)`,
		`CREATE INDEX IF NOT EXISTS idx_sql_procedures_proc_name_lower ON sql_procedures(LOWER(proc_name))`,
		`CREATE INDEX IF NOT EXISTS idx_sql_procedures_proc_name_trgm ON sql_procedures USING GIN (proc_name gin_trgm_ops)`,
		`CREATE INDEX IF NOT EXISTS idx_sql_tables_file_id ON sql_tables(file_id)`,
		`CREATE INDEX IF NOT EXISTS idx_sql_tables_table_name_lower ON sql_tables(LOWER(table_name))`,
		`CREATE INDEX IF NOT EXISTS idx_sql_tables_table_name_trgm ON sql_tables USING GIN (table_name gin_trgm_ops)`,
		`CREATE INDEX IF NOT EXISTS idx_sql_tables_table_name_file_id ON sql_tables(table_name, file_id)`,
		`CREATE INDEX IF NOT EXISTS idx_sql_columns_file_id ON sql_columns(file_id)`,
		`CREATE INDEX IF NOT EXISTS idx_sql_columns_table_name ON sql_columns(table_name)`,
		`CREATE INDEX IF NOT EXISTS idx_sql_column_definitions_file_id ON sql_column_definitions(file_id)`,
		`CREATE INDEX IF NOT EXISTS idx_sql_column_definitions_table_name ON sql_column_definitions(table_name)`,
		`CREATE INDEX IF NOT EXISTS idx_sql_column_definitions_lower_table_col ON sql_column_definitions(LOWER(table_name), LOWER(column_name))`,
		`CREATE INDEX IF NOT EXISTS idx_sql_index_definitions_file_id ON sql_index_definitions(file_id)`,
		`CREATE INDEX IF NOT EXISTS idx_sql_index_definitions_table_name ON sql_index_definitions(table_name)`,
		`CREATE INDEX IF NOT EXISTS idx_sql_index_definitions_name ON sql_index_definitions(index_name)`,
		`CREATE INDEX IF NOT EXISTS idx_sql_index_definition_fields_index_id ON sql_index_definition_fields(table_index_id)`,
		`CREATE INDEX IF NOT EXISTS idx_pas_units_file_id ON pas_units(file_id)`,
		`CREATE INDEX IF NOT EXISTS idx_pas_methods_unit_id ON pas_methods(unit_id)`,
		`CREATE INDEX IF NOT EXISTS idx_pas_methods_class_id ON pas_methods(class_id)`,
		`CREATE INDEX IF NOT EXISTS idx_pas_methods_method_name_lower ON pas_methods(LOWER(method_name))`,
		`CREATE INDEX IF NOT EXISTS idx_pas_methods_method_name_trgm ON pas_methods USING GIN (method_name gin_trgm_ops)`,
		`CREATE INDEX IF NOT EXISTS idx_h_files_defines_file_id ON h_files_defines(file_id)`,
		`CREATE INDEX IF NOT EXISTS idx_js_functions_file_id ON js_functions(file_id)`,
		`CREATE INDEX IF NOT EXISTS idx_js_functions_function_name_lower ON js_functions(LOWER(function_name))`,
		`CREATE INDEX IF NOT EXISTS idx_js_functions_function_name_trgm ON js_functions USING GIN (function_name gin_trgm_ops)`,
		`CREATE INDEX IF NOT EXISTS idx_js_constants_file_id ON js_constants(file_id)`,
		`CREATE INDEX IF NOT EXISTS idx_js_constants_name ON js_constants(constant_name)`,
		`CREATE INDEX IF NOT EXISTS idx_smf_instruments_file_id ON smf_instruments(file_id)`,
		`CREATE INDEX IF NOT EXISTS idx_smf_instruments_instrument_name_lower ON smf_instruments(LOWER(instrument_name))`,
		`CREATE INDEX IF NOT EXISTS idx_smf_instruments_instrument_name_trgm ON smf_instruments USING GIN (instrument_name gin_trgm_ops)`,
		`CREATE INDEX IF NOT EXISTS idx_dfm_forms_file_id ON dfm_forms(file_id)`,
		`CREATE INDEX IF NOT EXISTS idx_dfm_components_file_id ON dfm_components(file_id)`,
		`CREATE INDEX IF NOT EXISTS idx_dfm_components_form_id ON dfm_components(form_id)`,
		`CREATE INDEX IF NOT EXISTS idx_report_forms_file_id ON report_forms(file_id)`,
		`CREATE INDEX IF NOT EXISTS idx_report_forms_report_name_lower ON report_forms(LOWER(report_name))`,
		`CREATE INDEX IF NOT EXISTS idx_report_forms_report_name_trgm ON report_forms USING GIN (report_name gin_trgm_ops)`,
		`CREATE INDEX IF NOT EXISTS idx_report_fields_report_form_id ON report_fields(report_form_id)`,
		`CREATE INDEX IF NOT EXISTS idx_report_fields_field_name_lower ON report_fields(LOWER(field_name))`,
		`CREATE INDEX IF NOT EXISTS idx_report_fields_field_name_trgm ON report_fields USING GIN (field_name gin_trgm_ops)`,
		`CREATE INDEX IF NOT EXISTS idx_report_params_report_form_id ON report_params(report_form_id)`,
		`CREATE INDEX IF NOT EXISTS idx_report_params_param_name_lower ON report_params(LOWER(param_name))`,
		`CREATE INDEX IF NOT EXISTS idx_report_params_param_name_trgm ON report_params USING GIN (param_name gin_trgm_ops)`,
		`CREATE INDEX IF NOT EXISTS idx_vb_functions_report_form_id ON vb_functions(report_form_id)`,
		`CREATE INDEX IF NOT EXISTS idx_vb_functions_function_name_lower ON vb_functions(LOWER(function_name))`,
		`CREATE INDEX IF NOT EXISTS idx_vb_functions_function_name_trgm ON vb_functions USING GIN (function_name gin_trgm_ops)`,
		`CREATE INDEX IF NOT EXISTS idx_query_fragments_file_id ON query_fragments(file_id)`,
		`CREATE INDEX IF NOT EXISTS idx_query_fragments_file_line ON query_fragments(file_id, line_number)`,
		`CREATE INDEX IF NOT EXISTS idx_query_fragments_component_name_lower ON query_fragments(LOWER(component_name))`,
		`CREATE INDEX IF NOT EXISTS idx_query_fragments_component_name_trgm ON query_fragments USING GIN (component_name gin_trgm_ops)`,
		`CREATE INDEX IF NOT EXISTS idx_query_fragments_query_text_trgm ON query_fragments USING GIN (query_text gin_trgm_ops)`,
		`CREATE INDEX IF NOT EXISTS idx_include_directives_file_id ON include_directives(file_id)`,
		`CREATE INDEX IF NOT EXISTS idx_api_business_objects_file_id ON api_business_objects(file_id)`,
		`CREATE INDEX IF NOT EXISTS idx_api_business_objects_name ON api_business_objects(business_object)`,
		`CREATE INDEX IF NOT EXISTS idx_api_contracts_file_id ON api_contracts(file_id)`,
		`CREATE INDEX IF NOT EXISTS idx_api_contracts_name_kind ON api_contracts(contract_name, contract_kind)`,
		`CREATE INDEX IF NOT EXISTS idx_api_contracts_contract_name_lower ON api_contracts(LOWER(contract_name))`,
		`CREATE INDEX IF NOT EXISTS idx_api_contracts_contract_name_trgm ON api_contracts USING GIN (contract_name gin_trgm_ops)`,
		`CREATE INDEX IF NOT EXISTS idx_api_contracts_business_object ON api_contracts(business_object)`,
		`CREATE INDEX IF NOT EXISTS idx_api_contract_params_contract_id ON api_contract_params(contract_id)`,
		`CREATE INDEX IF NOT EXISTS idx_api_contract_tables_contract_id ON api_contract_tables(contract_id)`,
		`CREATE INDEX IF NOT EXISTS idx_api_contract_table_fields_table_id ON api_contract_table_fields(contract_table_id)`,
		`CREATE INDEX IF NOT EXISTS idx_api_business_object_params_file_id ON api_business_object_params(file_id)`,
		`CREATE INDEX IF NOT EXISTS idx_api_business_object_tables_file_id ON api_business_object_tables(file_id)`,
		`CREATE INDEX IF NOT EXISTS idx_api_business_object_table_indexes_table_id ON api_business_object_table_indexes(business_table_id)`,
		`CREATE INDEX IF NOT EXISTS idx_api_business_object_table_indexes_name ON api_business_object_table_indexes(index_name)`,
		`CREATE INDEX IF NOT EXISTS idx_api_business_object_table_index_fields_index_id ON api_business_object_table_index_fields(table_index_id)`,
		`CREATE INDEX IF NOT EXISTS idx_api_macro_invocations_file_id ON api_macro_invocations(file_id)`,
		`CREATE INDEX IF NOT EXISTS idx_api_macro_invocations_target_name ON api_macro_invocations(target_name)`,
		`CREATE INDEX IF NOT EXISTS idx_relations_source_type_id ON relations(source_type, source_id)`,
		`CREATE INDEX IF NOT EXISTS idx_relations_target_type_id ON relations(target_type, target_id)`,
		`CREATE INDEX IF NOT EXISTS idx_relations_source_type_relation ON relations(source_type, relation_type, source_id)`,
		`CREATE INDEX IF NOT EXISTS idx_relations_target_type_relation ON relations(target_type, relation_type, target_id)`,
		`CREATE INDEX IF NOT EXISTS idx_relations_relation_type ON relations(relation_type)`,
		`CREATE UNIQUE INDEX IF NOT EXISTS idx_ds_return_codes_code ON ds_return_codes(ret_code)`,
		`CREATE INDEX IF NOT EXISTS idx_rti_sessions_parsed_at ON rti_sessions(parsed_at DESC)`,
		`CREATE INDEX IF NOT EXISTS idx_rti_calls_session_proc ON rti_calls(session_id, procedure)`,
		`CREATE INDEX IF NOT EXISTS idx_rti_calls_session_elapsed ON rti_calls(session_id, elapsed_ms DESC)`,
		`CREATE INDEX IF NOT EXISTS idx_rti_calls_session_retval ON rti_calls(session_id, ret_val) WHERE ret_val IS NOT NULL AND ret_val <> 0`,
		`CREATE INDEX IF NOT EXISTS idx_rti_params_call_id ON rti_params(call_id)`,
		`CREATE INDEX IF NOT EXISTS idx_rti_checkpoints_call_id ON rti_checkpoints(call_id)`,
		`CREATE INDEX IF NOT EXISTS idx_rti_blog_blocks_call_id ON rti_blog_blocks(call_id)`,
		`CREATE INDEX IF NOT EXISTS idx_rti_blog_blocks_session_id ON rti_blog_blocks(session_id)`,
		`CREATE INDEX IF NOT EXISTS idx_rti_blog_tables_call_id ON rti_blog_tables(call_id)`,
		`CREATE INDEX IF NOT EXISTS idx_rti_blog_tables_session_id ON rti_blog_tables(session_id)`,
		`CREATE INDEX IF NOT EXISTS idx_rti_client_events_session_id ON rti_client_events(session_id)`,
		`CREATE INDEX IF NOT EXISTS idx_rti_client_events_session_kind ON rti_client_events(session_id, kind)`,
		`CREATE INDEX IF NOT EXISTS idx_rti_client_events_server_call_id ON rti_client_events(server_call_id)`,
		`CREATE INDEX IF NOT EXISTS idx_rti_client_events_session_ts ON rti_client_events(session_id, timestamp)`,
		`CREATE INDEX IF NOT EXISTS idx_rti_calls_session_entertime ON rti_calls(session_id, enter_time)`,
		// Удаление избыточных standalone-индексов, дублируемых составными с session_id
		`DROP INDEX IF EXISTS idx_rti_calls_session_id`,
		`DROP INDEX IF EXISTS idx_rti_calls_procedure`,
		`DROP INDEX IF EXISTS idx_rti_calls_elapsed_ms`,
		`DROP INDEX IF EXISTS idx_rti_calls_parent_id`,
		`CREATE INDEX IF NOT EXISTS idx_trc_sessions_parsed_at ON trc_sessions(parsed_at DESC)`,
		`CREATE INDEX IF NOT EXISTS idx_trc_events_session_spid ON trc_events(session_id, spid)`,
		`CREATE INDEX IF NOT EXISTS idx_trc_events_session_proc ON trc_events(session_id, procedure)`,
		`CREATE INDEX IF NOT EXISTS idx_trc_events_session_duration ON trc_events(session_id, duration_ms DESC)`,
		`CREATE INDEX IF NOT EXISTS idx_trc_events_session_parent ON trc_events(session_id, parent_id)`,
		`CREATE INDEX IF NOT EXISTS idx_trc_events_session_error ON trc_events(session_id) WHERE error IS NOT NULL AND error <> 0`,
		`CREATE INDEX IF NOT EXISTS idx_trc_events_session_event_name ON trc_events(session_id, event_name)`,
		// Удаление избыточных standalone-индексов, дублируемых составными с session_id
		`DROP INDEX IF EXISTS idx_trc_events_session_id`,
		`DROP INDEX IF EXISTS idx_trc_events_procedure`,
		`DROP INDEX IF EXISTS idx_trc_events_duration_ms`,
		`DROP INDEX IF EXISTS idx_trc_events_spid`,
		`DROP INDEX IF EXISTS idx_trc_events_event_sequence`,
	}

	for _, stmt := range statements {
		if _, err := db.Exec(stmt); err != nil {
			return fmt.Errorf("failed to initialize schema: %w", err)
		}
	}

	return nil
}
