package rti

// moduleIDMap — маппинг Module ID → Product Name.
// Источник: fa-commonfiles/CommonFiles/SERVER/Include/DEALMAIN.H
var moduleIDMap = map[int]string{
	10:  "Core",
	11:  "Sec",
	12:  "ESec",
	13:  "MoneyMarket_Ext",
	14:  "MBK",
	15:  "ForEx (MoneyMarket)",
	16:  "Bill",
	17:  "Loan",
	18:  "Depo",
	19:  "OFBU",
	20:  "Deposit",
	21:  "RKO (Payments)",
	22:  "CED",
	23:  "FUT",
	24:  "CB",
	25:  "HYP",
	26:  "EXP",
	27:  "Cost",
	28:  "Trust",
	29:  "Card",
	30:  "Metal",
	31:  "Cash",
	32:  "CashDoc",
	33:  "DDM",
	34:  "Safe",
	35:  "ExAct",
	36:  "Warranty",
	37:  "RMS",
	39:  "Consumer",
	40:  "Tax",
	41:  "Transfer",
	42:  "CR",
	43:  "MarginTrd",
	44:  "Limit",
	45:  "Factoring",
	46:  "CurrReg",
	47:  "Underwrite",
	48:  "BiZone",
	49:  "DocCredit",
	50:  "GL (GeneralLedger)",
	51:  "RetailCtr",
	52:  "PayInstr",
	53:  "BCH (LoanBureau)",
	54:  "Reports",
	55:  "Rating",
	56:  "UserProc",
	57:  "Archiver",
	58:  "ReservePortfolio",
	59:  "FrontGate",
	60:  "MessServer",
	61:  "CCntrlCore",
	62:  "CBA",
	63:  "GWClBank",
	64:  "SMCore",
	65:  "EArchDoc",
	66:  "Netting_Ext",
	67:  "PoolMgr",
	68:  "SecurityIssue",
	69:  "Rapida",
	70:  "QIWI",
	71:  "ExchangeRate",
	72:  "Deposit_Ext",
	73:  "StockMarket_Ext",
	74:  "InOutDoc_Ext",
	75:  "SMCore_Ext",
	76:  "Consumer_Ext",
	77:  "Integrates",
	78:  "GAAP",
	79:  "PayCentre",
	80:  "FICore",
	81:  "InOutDoc",
	82:  "Pooling",
	83:  "IR_CC_SWAP",
	84:  "FinControl",
	85:  "CreditCore",
	86:  "AML",
	87:  "CtrTrnsf",
	88:  "Constant",
	89:  "TestAPI",
	90:  "EMS",
	91:  "AccrualCore",
	92:  "Common",
	93:  "SystemMonitoring",
	94:  "CrnControl",
	95:  "Invoice",
	205: "Netting",
	400: "FIAccounting",
	405: "Insurance_Ext",
}

// ModuleNameByID возвращает имя продукта по Module ID.
// Если ID не найден, возвращает "Unknown".
func ModuleNameByID(id int) string {
	if name, ok := moduleIDMap[id]; ok {
		return name
	}
	return "Unknown"
}
