//go:build ignore

// Команда gen_xel_mapping читает CSV-таблицу соответствий XE-событий/actions
// событиям и колонкам SQL Server Profiler (TRC) и генерирует
// xel_event_map_generated.go с двумя картами:
//   - xeEventNameToClass: xe_event_name -> trace_event_id (TRC EventClass).
//     Для xe_event_name, встречающегося в CSV с несколькими trace_event_id,
//     берётся МИНИМАЛЬНЫЙ trace_event_id (правило первичного маппинга,
//     см. Phase 1 плана xel-parser-impl-2640ba.md).
//   - xeActionNameToColumn: xe_action_name -> TRC ColumnID. Берётся ПЕРВОЕ
//     встреченное в файле сопоставление; при обнаружении конфликта
//     (одно и то же имя action ссылается на разные ColumnID в разных
//     строках CSV) генератор печатает предупреждение в stderr, но не
//     прерывает генерацию — конфликты проверяются отдельным тестом
//     TestXELEventMapGenerated_NoCollisions.
//
// Запуск: go generate ./internal/trc/... (см. go:generate в xel_format.go).
package main

import (
	"encoding/csv"
	"fmt"
	"io"
	"log"
	"os"
	"sort"
	"strconv"
	"strings"
	"time"
)

const csvRelPath = "../../Modifications/Эквиваленты расширенных событий событиям трассировки SQL.csv"
const outPath = "xel_event_map_generated.go"

func main() {
	f, err := os.Open(csvRelPath)
	if err != nil {
		log.Fatalf("open %s: %v", csvRelPath, err)
	}
	defer f.Close()

	r := csv.NewReader(f)
	r.Comma = ';'
	r.FieldsPerRecord = -1
	r.LazyQuotes = true

	eventMinClass := map[string]int{}
	actionColumn := map[string]int{}
	actionAllColumns := map[string]map[int]bool{}

	for {
		rec, err := r.Read()
		if err == io.EOF {
			break
		}
		if err != nil {
			log.Fatalf("csv read: %v", err)
		}
		if len(rec) < 7 {
			continue
		}
		traceIDStr := strings.TrimSpace(rec[0])
		xeEvent := strings.TrimSpace(rec[3])
		colIDStr := strings.TrimSpace(rec[4])
		xeAction := strings.TrimSpace(rec[6])

		if xeEvent != "" && xeEvent != "NULL" && traceIDStr != "NULL" {
			if id, err := strconv.Atoi(traceIDStr); err == nil {
				if cur, ok := eventMinClass[xeEvent]; !ok || id < cur {
					eventMinClass[xeEvent] = id
				}
			}
		}

		if xeAction != "" && xeAction != "NULL" && colIDStr != "NULL" {
			if colID, err := strconv.Atoi(colIDStr); err == nil {
				if _, ok := actionColumn[xeAction]; !ok {
					actionColumn[xeAction] = colID
				}
				if actionAllColumns[xeAction] == nil {
					actionAllColumns[xeAction] = map[int]bool{}
				}
				actionAllColumns[xeAction][colID] = true
			}
		}
	}

	conflicts := 0
	for name, cols := range actionAllColumns {
		if len(cols) > 1 {
			conflicts++
			ids := make([]int, 0, len(cols))
			for id := range cols {
				ids = append(ids, id)
			}
			sort.Ints(ids)
			log.Printf("warning: action %q встречается с разными ColumnID: %v (взят первый: %d)", name, ids, actionColumn[name])
		}
	}
	if conflicts > 0 {
		log.Printf("всего конфликтов action->ColumnID: %d (см. warnings выше)", conflicts)
	}

	out, err := os.Create(outPath)
	if err != nil {
		log.Fatalf("create %s: %v", outPath, err)
	}
	defer out.Close()

	fmt.Fprintf(out, "// Code generated by gen_xel_mapping.go via go:generate; DO NOT EDIT.\n")
	fmt.Fprintf(out, "// Источник: Modifications/Эквиваленты расширенных событий событиям трассировки SQL.csv\n")
	fmt.Fprintf(out, "// Сгенерировано: %s\n", time.Now().Format("2006-01-02"))
	fmt.Fprintf(out, "\npackage trc\n\n")

	fmt.Fprintf(out, "// xeEventNameToClass — соответствие xe_event_name -> trace_event_id (TRC\n")
	fmt.Fprintf(out, "// EventClass). Для xe_event_name с несколькими trace_event_id в источнике\n")
	fmt.Fprintf(out, "// взят МИНИМАЛЬНЫЙ trace_event_id (правило первичного маппинга).\n")
	fmt.Fprintf(out, "// XE-события без TRC-эквивалента (напр. wait_completed, wait_info) в этой\n")
	fmt.Fprintf(out, "// карте отсутствуют.\n")
	fmt.Fprintf(out, "var xeEventNameToClass = map[string]int{\n")
	writeSortedIntMap(out, eventMinClass)
	fmt.Fprintf(out, "}\n\n")

	fmt.Fprintf(out, "// xeActionNameToColumn — соответствие xe_action_name -> TRC ColumnID.\n")
	fmt.Fprintf(out, "// При наличии конфликтующих ColumnID для одного action-имени в источнике\n")
	fmt.Fprintf(out, "// взято первое встреченное значение (см. warnings генератора).\n")
	fmt.Fprintf(out, "var xeActionNameToColumn = map[string]int{\n")
	writeSortedIntMap(out, actionColumn)
	fmt.Fprintf(out, "}\n")

	log.Printf("сгенерировано: %d событий, %d actions -> %s", len(eventMinClass), len(actionColumn), outPath)
}

func writeSortedIntMap(out io.Writer, m map[string]int) {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		fmt.Fprintf(out, "\t%q: %d,\n", k, m[k])
	}
}
